Mx to mx write
ezagroba/docs pull request #1
Opened 2021-09-21 12:10 UTC by tobiasmihelcic

Adding documentation for Studio Pro part of mx to mx write.

2021-09-22 12:43 UTC, paulmendix commented on content/howto/write-data/index.md
> +Just like in the Catalog you can see the CRUD capabilities of entities, attributes, and associations inside the Data Hub pane of the Mendix Studio Pro.
I'm no expert, but I think replacing `inside the Data Hub pane of the Mendix Studio Pro.` by `inside the Data Hub pane of Studio Pro.` makes the sentence a bit smoother.

2021-09-22 12:52 UTC, paulmendix commented on content/howto/write-data/index.md
> + Version 2: If Studio Pro supports displaying CRUD capabilities, then the values correspond to the values in the Catalog
What about?

`In Studio Pro you might not see the same CRUD capabilities highlighted as in the Data Hub Catalog. A CRUD capability will only be highlighted when it is both supported by the contract and also by Studio Pro.`

2021-09-22 12:54 UTC, paulmendix commented on content/howto/write-data/index.md
> + 3. Drag an entity to the Domain Model.
What about `Drag the entity to the domain model.`

2021-09-22 15:15 UTC, paulmendix requested changes

2021-09-22 15:15 UTC, paulmendix commented on content/howto/write-data/index.md
> + 2. Select your entity from the Data Hub pane. If you're not seeing any or enough results, try enabling the **Show development environment** filter on your search.
What about replacing `If you're not seeing any or enough results, try enabling the **Show development environment** filter on your search.` by `By default it shows only results published to the production environment. If you also want to see results from other environments, please click the filter button and check the **Show development environment** checkbox.`?

2021-09-22 15:15 UTC, paulmendix commented on content/howto/write-data/index.md
> + 4. Consume that entity anywhere in your module just like a local entity. This is based on the CRUD capabilities.
What about changing this to: `Now you have an external entity in your domain model. Depending on the capabilities, for example the CRUD capabilities, you can use them to model your app as you would normally do.`

2021-09-22 15:15 UTC, paulmendix commented on content/howto/write-data/index.md
> + Is this part necessary??: If this is the first entity from a Service inside the module, then this action will also add the Service to the module.
I don't think these parts are necessary for now

2021-09-22 17:25 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> +Just like in the Catalog you can see the CRUD capabilities of entities, attributes, and associations inside the Data Hub pane of the Mendix Studio Pro.
Yes, that does sound smoother, `the Mendix` was not adding any value.

2021-09-22 17:26 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> + Version 2: If Studio Pro supports displaying CRUD capabilities, then the values correspond to the values in the Catalog
Your version sounds good. I've changed it.

2021-09-22 17:26 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> + 3. Drag an entity to the Domain Model.
Yes, that makes sense. But Data Hub is capitalized everywhere, correct?

2021-09-22 17:26 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> + 2. Select your entity from the Data Hub pane. If you're not seeing any or enough results, try enabling the **Show development environment** filter on your search.
That sounds better, but I still think we can do better here.
For now I've changed it to your version, but I'll think about it some more.

2021-09-22 17:28 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> + 4. Consume that entity anywhere in your module just like a local entity. This is based on the CRUD capabilities.
Does it make sense to write `for example the CRUD capabilities` here?
What other capabilities can we have besides validated?

2021-09-22 17:28 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> + Is this part necessary??: If this is the first entity from a Service inside the module, then this action will also add the Service to the module.
I removed them for now.

2021-09-29 10:08 UTC, paulmendix commented on content/refguide/external-entities.md
> +If there is a newer version of a consumed service becomes available in the Data Hub Catalog, this will be indicated in the **Data Hub** pane by an update arrow against the service name. For more info
Let's replace `If there is a newer version of a consumed service becomes available` by `When a new version of a consumed service becomes available` to make the sentence a bit smoother.

And let's replace `an update arrow against the service name` by `an update arrow next to the service name`.

2021-09-29 10:09 UTC, paulmendix commented on content/refguide/data-hub-pane.md
> +If the entity, association, or attribute support any of the capabilities and it is also supported by Studio Pro, then it will be displayed in the Data Hub pane.
I think it it should be `supports` instead of `support`

2021-09-29 10:18 UTC, paulmendix commented on content/howto/write-data/index.md
> +In Studio Pro you might not see the same CRUD capabilities highlighted as in the Data Hub Catalog. A CRUD capability will only be highlighted when it is both supported by the contract and also by Stu
What about `In Studio Pro you might not see all the CRUD capabilities highlighted that are highlighted in Data Hub Catalog.` Currently it sounds like different capabilities can be highlighted, while it can only be the same capabilities or less.

2021-09-29 12:05 UTC, paulmendix commented on content/refguide/data-hub-pane.md
> +When no search string has been specified in the **Data Hub** pane, the **Used in your app** section is displayed. This shows the consumed services and the external entities used in the current projec
Let's change that to `When you do not enter search text in the **Data Hub** pane, ` because search string is developer language

2021-09-29 12:07 UTC, paulmendix commented on content/refguide/data-hub-pane.md
> +* ** Gray shield icon** if the service or entity is validated in the Catalog.
In the text below, only `Blue Update Service` is emphasized, and `icon` is not. Good to make `Gray shield icon` consistent with that.

2021-09-29 12:09 UTC, paulmendix commented on content/howto/write-data/index.md
> +Just like in the Catalog you can see the CRUD capabilities of entities, attributes, and associations inside the Data Hub pane of the Mendix Studio Pro.
All good

2021-09-29 12:09 UTC, paulmendix commented on content/howto/write-data/index.md
> + Version 2: If Studio Pro supports displaying CRUD capabilities, then the values correspond to the values in the Catalog
Thanks for updating it. I added another comment to my own suggestion.

2021-09-29 12:13 UTC, paulmendix commented on content/howto/write-data/index.md
> + 2. Select your entity from the Data Hub pane. If you're not seeing any or enough results, try enabling the **Show development environment** filter on your search.
Okay

2021-09-29 12:13 UTC, paulmendix commented on content/howto/write-data/index.md
> + Is this part necessary??: If this is the first entity from a Service inside the module, then this action will also add the Service to the module.
Okay

2021-09-29 12:14 UTC, paulmendix commented on content/howto/write-data/index.md
> + 4. Consume that entity anywhere in your module just like a local entity. This is based on the CRUD capabilities.
Attributes can be filterable or sortable, entities might get countable capabilities in the future

2021-09-30 13:11 UTC, tobiasmihelcic commented on content/refguide/external-entities.md
> +If there is a newer version of a consumed service becomes available in the Data Hub Catalog, this will be indicated in the **Data Hub** pane by an update arrow against the service name. For more info
Done.

2021-09-30 13:11 UTC, tobiasmihelcic commented on content/refguide/data-hub-pane.md
> +If the entity, association, or attribute support any of the capabilities and it is also supported by Studio Pro, then it will be displayed in the Data Hub pane.
Changed.

2021-09-30 13:12 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> +In Studio Pro you might not see the same CRUD capabilities highlighted as in the Data Hub Catalog. A CRUD capability will only be highlighted when it is both supported by the contract and also by Stu
I agree that it sounded like it could support more.
I've changed it now and it reads & feels much better.

2021-09-30 13:12 UTC, tobiasmihelcic commented on content/refguide/data-hub-pane.md
> +When no search string has been specified in the **Data Hub** pane, the **Used in your app** section is displayed. This shows the consumed services and the external entities used in the current projec
Changed.

2021-09-30 13:13 UTC, tobiasmihelcic commented on content/refguide/data-hub-pane.md
> +* ** Gray shield icon** if the service or entity is validated in the Catalog.
Good catch, changed.

2021-10-05 11:06 UTC, paulmendix commented
I checked all the changes. I think it looks good.

2021-10-05 12:34 UTC, ezagroba commented on content/howto/write-data/index.md
> +1. Notice the highlighted **CRUD** letters next to the entity name in the search panel and in the detailed information in the center. The purple letters indicate which operations are supported. The g
```suggestion
1. Notice the highlighted **CRUD** letters next to the entity name in the search panel and in the detailed information in the center. The purple letters indicate which operations are supported. The gray letters indicate which are not. Hover over the letters to see which operations are supported:
```

You had gray somewhere else. Mendix generally goes with American spellings. Grey is British.

2021-10-05 12:34 UTC, ezagroba commented on content/howto/write-data/index.md
> + 1. Inside the Data Hub pane start typing in the search field
```suggestion
 1. Inside the Data Hub pane, start typing in the search field.
```

2021-10-05 13:09 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> +1. Notice the highlighted **CRUD** letters next to the entity name in the search panel and in the detailed information in the center. The purple letters indicate which operations are supported. The g
That is really good to know for the future. Thanks!

2021-10-05 13:09 UTC, tobiasmihelcic commented on content/howto/write-data/index.md
> + 1. Inside the Data Hub pane start typing in the search field
Changed.

2021-10-05 13:33 UTC, merged